### ISSUE TITLE
Bypass 

### ISSUE THREAD

**Issue by Ralfiga** [builtbybel/ReadySunValley#17]
Funktioniert bei mir nicht.TPM wird weiterhin als Fehler erkannt.Bei Windows Insider wird mir sofort eine Fehlermeldung bezüglich Win 11 gezeigt.Auch andere Tools zeigen es weiterhin an.

**Comment by Belim** [comment]
:thinking: verdammt! im dev chanel hat es bei mir noch geklappt. die insider kriegt man aktuell ja nur im release channel.

die hardwareseitige tpm erkennung wird auch trotz bypass auf fehler laufen.  das ist schon so richtig, da die hardware dir ja auch weiterhin fehlt. es ist ja nur ein softwarehack.  wir sollten hier auf weiteres feedback warten...

**Comment by Ralfiga** [comment]
Trotzdem Danke für deine Antwort.

**Comment by Oleg-Chashko** [comment]
- You guys don't seem to know why, this bypass in the registry was made and what it affects.
_Bei Windows Insider wird mir sofort eine Fehlermeldung bezüglich Win 11 gezeigt. Auch andere Tools zeigen es weiterhin an._ -> 
1. This "bypass" should also not affect the compatibility checker readings at this point in time.
2. And it should not affect Windows for developers. As in Windows for developers at the moment all the artificial restrictions have been removed!

- "Bypass" was needed to install the first "illegally" version of Windows 11.
There were three possible ways to install a version of Windows 11:
1. Compatible computers. (For internal Microsoft purposes).
2. "Bypass" for incompatible computers. (For internal Microsoft purposes)
3. File Substitution, in ISO image of Windows 11 from Windows 10.(Community)

The reasoning behind "Bypass", at this point in time, is whether bypass is needed, maybe it is, but I don't know who needs it.
Keep in mind that the "Bypass" may not work anymore by the time Windows 11 is released. And it won't be needed, because Microsoft will change its requirements for Windows 11 as usual. And keep in mind that (the Community will fix what Microsoft didn't want to do).

- Conclusion: Install the developer version of Windows 11 on a blank disk and you do not need a "Bypass".

It seems to me that you can close this topic?

P.S.:I hope a new cauldron in hell is being prepared for Microsoft, for the Registry and for these Innovations.😈🔥

**Comment by Oleg-Chashko** [comment]
Those who really need Windows 11.

Windows 11, Version 21H2 Build 22000.65.co_release_svc_im.210703-0754 with CumulativeUpdate #KB5004745:

https://cloud.mail.ru/public/9uWp/iVQ4yEdoq/

**The assembly includes:**
![E5zDpwkWUAYKz0G](https://user-images.githubusercontent.com/62497891/125814027-a3983b1a-b6a3-4b97-bfc4-a303ff35c4f5.png)

**Comment by Belim** [comment]
well, you're the boss...thanks for the clarification 😁

**Comment by Oleg-Chashko** [comment]
I am glad to help.😁
