### ISSUE TITLE
You need to provide credit. 

### ISSUE THREAD

**Issue by d3n4c3** [builtbybel/ReadySunValley#3]
If you're going to basically copy my code line for line you should probably credit me in your repo and application. Considering you've been releasing it on software websites without mention of my authorship.  I'd be okay with a link to the original github added in your program.

**Comment by Belim** [comment]
whats this https://github.com/builtbybel/moin-11#credits ?

**Comment by Belim** [comment]
hmm https://github.com/builtbybel/moin-11#credits

**Comment by d3n4c3** [comment]
That's hardly a credit. You're saying you based it off of it. You took the code line for line.  You really should provide credit in your compiled application that you're distributing as well. It's just a good faith practice. In the future I hope you consider the worth of others a bit more when doing things like this. We could have collaborated together on the project instead of you copy pasting it to a new repo, making some minor changes, stamping your name on it, and distributing it to software publishers.

**Comment by d3n4c3** [comment]
Also you've added a MIT license and your own copyright to my code without even mentioning me in the license information. I hope you really understand how truly bad that is.

**Comment by Belim** [comment]
:sleepy: https://github.com/builtbybel/moin-11/blob/main/LICENSE

**Comment by d3n4c3** [comment]
You don't have to give me full credit but you can link to me at least. Thank you for understanding my point though.

**Comment by Belim** [comment]
actually i just wanted to push your code, because no one else on this earth would have seen it. i discovered it by chance when i wanted to deal with tpm, but found no way to access it in .net. i'm honest and can tell you that i spent 3 minutes on the code and 11 more on the gui during the work breaks and actually it was finished for me. the basic idea is not bad so i went on again.

I will also mention you in the program. You were the first to come up with the idea, you're right! although today I discovered a tool called whynotwin11, which does the same but it is just an autoit script and I don't like it at all. maybe we can do it better :grin:
